/**
 * Lucide 图标注册表 — PocketBook
 *
 * 规则：
 *   - 图标名使用 kebab-case（与 lucide 官方名称一致）
 *   - 组件引用使用 PascalCase
 *   - 仅注册需要的图标，避免全量打包
 *   - 所有新增图标须同步添加中文名（ICON_LABELS）
 */
import {
  // ─── 餐饮 ─────────────────────────────────────────────────────────
  Utensils,
  UtensilsCrossed,
  Coffee,
  Cookie,
  Pizza,
  Apple,
  Beef,
  Sandwich,
  Soup,
  Wine,
  Cake,
  IceCreamCone,
  ChefHat,
  GlassWater,
  Egg,
  Beer,
  Milk,
  // ─── 出行 ─────────────────────────────────────────────────────────
  Car,
  Bus,
  Plane,
  Bike,
  Train,
  Truck,
  Ship,
  Fuel,
  MapPin,
  Map,
  Navigation,
  Compass,
  Rocket,
  Tent,
  // ─── 财务 ─────────────────────────────────────────────────────────
  Banknote,
  Wallet,
  CreditCard,
  TrendingUp,
  TrendingDown,
  PiggyBank,
  Receipt,
  Percent,
  DollarSign,
  HandCoins,
  Coins,
  Calculator,
  Scale,
  Landmark,
  Briefcase,
  // ─── 购物 / 时尚 ──────────────────────────────────────────────────
  ShoppingBag,
  ShoppingCart,
  Package,
  Tag,
  Shirt,
  Gem,
  Glasses,
  Watch,
  Backpack,
  // ─── 居家 ─────────────────────────────────────────────────────────
  Home,
  House,
  Building2,
  Lightbulb,
  DoorOpen,
  Wrench,
  Hammer,
  Key,
  Lock,
  Bed,
  Bath,
  Droplets,
  Flame,
  // ─── 健康 ─────────────────────────────────────────────────────────
  HeartPulse,
  Stethoscope,
  Pill,
  Activity,
  Dumbbell,
  Hospital,
  Thermometer,
  Syringe,
  HeartHandshake,
  Shield,
  ShieldCheck,
  // ─── 娱乐 ─────────────────────────────────────────────────────────
  Film,
  Music,
  Trophy,
  Gamepad2,
  Gamepad,
  Headphones,
  Camera,
  Ticket,
  Tv,
  Video,
  Guitar,
  Dice5,
  Clapperboard,
  // ─── 运动 / 户外 ──────────────────────────────────────────────────
  Mountain,
  Snowflake,
  Waves,
  // ─── 工作 / 职业 ──────────────────────────────────────────────────
  Target,
  Award,
  Medal,
  Flag,
  Clipboard,
  ListChecks,
  FileText,
  // ─── 学习 ─────────────────────────────────────────────────────────
  GraduationCap,
  BookOpen,
  BookMarked,
  Book,
  Pencil,
  Globe,
  Microscope,
  // ─── 数码 / 科技 ──────────────────────────────────────────────────
  Smartphone,
  Laptop,
  Monitor,
  Printer,
  Phone,
  Mail,
  Keyboard,
  Cpu,
  HardDrive,
  Wifi,
  Zap,
  // ─── 自然 / 天气 ──────────────────────────────────────────────────
  Leaf,
  Cloud,
  Wind,
  TreePine,
  Sprout,
  Flower2,
  Sun,
  Moon,
  Sunrise,
  // ─── 宠物 ─────────────────────────────────────────────────────────
  Cat,
  Dog,
  Bird,
  Fish,
  Baby,
  // ─── 庆典 / 特殊 ──────────────────────────────────────────────────
  Gift,
  Sparkles,
  PartyPopper,
  Crown,
  Star,
  Heart,
  Smile,
  // ─── 通用 UI（导航 / 系统用，不参与分类选择）─────────────────────
  Folder,
  Plus,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Search,
  Settings,
  Bell,
  Upload,
  Download,
  Share2,
  Edit2,
  Trash2,
  MoreHorizontal,
  MoreVertical,
  CalendarDays,
  FilePenLine,
  Clock,
  AlertCircle,
  Info,
  Scissors,
  Bookmark,
  Timer,
} from "lucide-react-native";
import type { LucideProps } from "lucide-react-native";

export type LucideIcon = React.ComponentType<LucideProps>;

/** kebab-case 图标名 → Lucide 组件（Icon 选择器的唯一注册表） */
export const ICON_MAP: Record<string, LucideIcon> = {
  // ─── 餐饮 ─────────────────────────────────────────────────────────
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  coffee: Coffee,
  cookie: Cookie,
  pizza: Pizza,
  apple: Apple,
  beef: Beef,
  sandwich: Sandwich,
  soup: Soup,
  wine: Wine,
  cake: Cake,
  "ice-cream-cone": IceCreamCone,
  "chef-hat": ChefHat,
  "glass-water": GlassWater,
  egg: Egg,
  beer: Beer,
  milk: Milk,
  // ─── 出行 ─────────────────────────────────────────────────────────
  car: Car,
  bus: Bus,
  plane: Plane,
  bike: Bike,
  train: Train,
  truck: Truck,
  ship: Ship,
  fuel: Fuel,
  "map-pin": MapPin,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  rocket: Rocket,
  tent: Tent,
  // ─── 财务 ─────────────────────────────────────────────────────────
  banknote: Banknote,
  wallet: Wallet,
  "credit-card": CreditCard,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  percent: Percent,
  "dollar-sign": DollarSign,
  "hand-coins": HandCoins,
  coins: Coins,
  calculator: Calculator,
  scale: Scale,
  landmark: Landmark,
  briefcase: Briefcase,
  // ─── 购物 / 时尚 ──────────────────────────────────────────────────
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  package: Package,
  tag: Tag,
  shirt: Shirt,
  gem: Gem,
  glasses: Glasses,
  watch: Watch,
  backpack: Backpack,
  // ─── 居家 ─────────────────────────────────────────────────────────
  home: Home,
  house: House,
  "building-2": Building2,
  lightbulb: Lightbulb,
  "door-open": DoorOpen,
  wrench: Wrench,
  hammer: Hammer,
  key: Key,
  lock: Lock,
  bed: Bed,
  bath: Bath,
  droplets: Droplets,
  flame: Flame,
  // ─── 健康 ─────────────────────────────────────────────────────────
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  activity: Activity,
  dumbbell: Dumbbell,
  hospital: Hospital,
  thermometer: Thermometer,
  syringe: Syringe,
  "heart-handshake": HeartHandshake,
  shield: Shield,
  "shield-check": ShieldCheck,
  // ─── 娱乐 ─────────────────────────────────────────────────────────
  film: Film,
  music: Music,
  trophy: Trophy,
  "gamepad-2": Gamepad2,
  gamepad: Gamepad,
  headphones: Headphones,
  camera: Camera,
  ticket: Ticket,
  tv: Tv,
  video: Video,
  guitar: Guitar,
  "dice-5": Dice5,
  clapperboard: Clapperboard,
  // ─── 运动 / 户外 ──────────────────────────────────────────────────
  mountain: Mountain,
  snowflake: Snowflake,
  waves: Waves,
  // ─── 工作 / 职业 ──────────────────────────────────────────────────
  target: Target,
  award: Award,
  medal: Medal,
  flag: Flag,
  clipboard: Clipboard,
  "list-checks": ListChecks,
  "file-text": FileText,
  // ─── 学习 ─────────────────────────────────────────────────────────
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  book: Book,
  pencil: Pencil,
  globe: Globe,
  microscope: Microscope,
  // ─── 数码 / 科技 ──────────────────────────────────────────────────
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  phone: Phone,
  mail: Mail,
  keyboard: Keyboard,
  cpu: Cpu,
  "hard-drive": HardDrive,
  wifi: Wifi,
  zap: Zap,
  // ─── 自然 / 天气 ──────────────────────────────────────────────────
  leaf: Leaf,
  cloud: Cloud,
  wind: Wind,
  "tree-pine": TreePine,
  sprout: Sprout,
  "flower-2": Flower2,
  sun: Sun,
  moon: Moon,
  sunrise: Sunrise,
  // ─── 宠物 ─────────────────────────────────────────────────────────
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  baby: Baby,
  // ─── 庆典 / 特殊 ──────────────────────────────────────────────────
  gift: Gift,
  sparkles: Sparkles,
  "party-popper": PartyPopper,
  crown: Crown,
  star: Star,
  heart: Heart,
  smile: Smile,
  // ─── 通用 UI ──────────────────────────────────────────────────────
  folder: Folder,
  plus: Plus,
  x: X,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  search: Search,
  settings: Settings,
  bell: Bell,
  upload: Upload,
  download: Download,
  share2: Share2,
  "edit-2": Edit2,
  "trash-2": Trash2,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "calendar-days": CalendarDays,
  "file-pen-line": FilePenLine,
  clock: Clock,
  "alert-circle": AlertCircle,
  info: Info,
  scissors: Scissors,
  bookmark: Bookmark,
  timer: Timer,
};

/**
 * 图标中文名称映射
 * - 在 UI 单元格内显示友好中文标签
 * - 支持按中文关键词搜索图标
 */
export const ICON_LABELS: Record<string, string> = {
  // ─── 餐饮 ─────────────────────────────────────────────────────────
  utensils: "餐具",
  "utensils-crossed": "饮食",
  coffee: "咖啡",
  cookie: "点心",
  pizza: "披萨",
  apple: "水果",
  beef: "肉类",
  sandwich: "三明治",
  soup: "汤",
  wine: "酒水",
  cake: "蛋糕",
  "ice-cream-cone": "冰淇淋",
  "chef-hat": "厨师",
  "glass-water": "饮水",
  egg: "鸡蛋",
  beer: "啤酒",
  milk: "牛奶",
  // ─── 出行 ─────────────────────────────────────────────────────────
  car: "汽车",
  bus: "公交",
  plane: "飞机",
  bike: "自行车",
  train: "火车",
  truck: "货车",
  ship: "轮船",
  fuel: "加油",
  "map-pin": "地点",
  map: "地图",
  navigation: "导航",
  compass: "指南针",
  rocket: "火箭",
  tent: "露营",
  // ─── 财务 ─────────────────────────────────────────────────────────
  banknote: "钞票",
  wallet: "钱包",
  "credit-card": "信用卡",
  "trending-up": "增长",
  "trending-down": "下跌",
  "piggy-bank": "存钱罐",
  receipt: "收据",
  percent: "折扣",
  "dollar-sign": "货币",
  "hand-coins": "转账",
  coins: "硬币",
  calculator: "计算器",
  scale: "天平",
  landmark: "银行",
  briefcase: "职业",
  // ─── 购物 / 时尚 ──────────────────────────────────────────────────
  "shopping-bag": "购物袋",
  "shopping-cart": "购物车",
  package: "包裹",
  tag: "标签",
  shirt: "服装",
  gem: "珠宝",
  glasses: "眼镜",
  watch: "手表",
  backpack: "背包",
  // ─── 居家 ─────────────────────────────────────────────────────────
  home: "家",
  house: "房屋",
  "building-2": "建筑",
  lightbulb: "电费",
  "door-open": "门",
  wrench: "维修",
  hammer: "修缮",
  key: "钥匙",
  lock: "安全",
  bed: "睡眠",
  bath: "浴室",
  droplets: "水费",
  flame: "燃气",
  // ─── 健康 ─────────────────────────────────────────────────────────
  "heart-pulse": "健康",
  stethoscope: "就医",
  pill: "药品",
  activity: "活动",
  dumbbell: "健身",
  hospital: "医院",
  thermometer: "体温",
  syringe: "注射",
  "heart-handshake": "关怀",
  shield: "防护",
  "shield-check": "保险",
  // ─── 娱乐 ─────────────────────────────────────────────────────────
  film: "电影",
  music: "音乐",
  trophy: "奖杯",
  "gamepad-2": "游戏",
  gamepad: "手柄",
  headphones: "耳机",
  camera: "相机",
  ticket: "票务",
  tv: "电视",
  video: "视频",
  guitar: "吉他",
  "dice-5": "骰子",
  clapperboard: "影视",
  // ─── 运动 / 户外 ──────────────────────────────────────────────────
  mountain: "登山",
  snowflake: "冰雪",
  waves: "游泳",
  // ─── 工作 / 职业 ──────────────────────────────────────────────────
  target: "目标",
  award: "奖励",
  medal: "奖章",
  flag: "里程碑",
  clipboard: "记录",
  "list-checks": "清单",
  "file-text": "文件",
  // ─── 学习 ─────────────────────────────────────────────────────────
  "graduation-cap": "毕业",
  "book-open": "读书",
  "book-marked": "书签",
  book: "书本",
  pencil: "写作",
  globe: "旅行",
  microscope: "研究",
  // ─── 数码 / 科技 ──────────────────────────────────────────────────
  smartphone: "手机",
  laptop: "笔记本",
  monitor: "显示器",
  printer: "打印机",
  phone: "电话",
  mail: "邮件",
  keyboard: "键盘",
  cpu: "芯片",
  "hard-drive": "硬盘",
  wifi: "网络",
  zap: "闪电",
  // ─── 自然 / 天气 ──────────────────────────────────────────────────
  leaf: "自然",
  cloud: "天气",
  wind: "风",
  "tree-pine": "松树",
  sprout: "成长",
  "flower-2": "花朵",
  sun: "太阳",
  moon: "月亮",
  sunrise: "日出",
  // ─── 宠物 ─────────────────────────────────────────────────────────
  cat: "猫",
  dog: "狗",
  bird: "鸟",
  fish: "鱼",
  baby: "育儿",
  // ─── 庆典 / 特殊 ──────────────────────────────────────────────────
  gift: "礼物",
  sparkles: "闪耀",
  "party-popper": "庆祝",
  crown: "皇冠",
  star: "收藏",
  heart: "喜欢",
  smile: "微笑",
  // ─── 通用 UI ──────────────────────────────────────────────────────
  folder: "文件夹",
  plus: "新增",
  x: "关闭",
  check: "确认",
  "chevron-left": "向左",
  "chevron-right": "向右",
  "chevron-down": "向下",
  "chevron-up": "向上",
  search: "搜索",
  settings: "设置",
  bell: "提醒",
  upload: "上传",
  download: "下载",
  share2: "分享",
  "edit-2": "编辑",
  "trash-2": "删除",
  "more-horizontal": "更多",
  "more-vertical": "更多选项",
  "calendar-days": "日历",
  "file-pen-line": "编辑文件",
  clock: "时间",
  "alert-circle": "警告",
  info: "信息",
  scissors: "剪刀",
  bookmark: "收藏夹",
  timer: "计时器",
};

export type IconGroup = { label: string; icons: string[] };

/**
 * 图标选择器分类分组
 * 每组图标对应一个筛选 Chip；「全部」组在运行时由 ALL_ICON_NAMES 动态生成。
 */
export const ICON_GROUPS: IconGroup[] = [
  {
    label: "通用",
    icons: [
      "folder", "star", "heart", "smile", "crown", "gift",
      "party-popper", "sparkles", "bookmark", "flag", "bell",
      "clock", "calendar-days", "map-pin", "globe", "camera",
      "settings", "search", "tag",
    ],
  },
  {
    label: "财务",
    icons: [
      "banknote", "wallet", "credit-card", "coins", "hand-coins",
      "trending-up", "trending-down", "piggy-bank", "receipt",
      "percent", "dollar-sign", "calculator", "scale", "landmark",
      "briefcase",
    ],
  },
  {
    label: "餐饮",
    icons: [
      "utensils", "utensils-crossed", "chef-hat", "coffee", "cookie",
      "pizza", "apple", "beef", "sandwich", "soup", "wine", "cake",
      "ice-cream-cone", "glass-water", "egg", "beer", "milk",
    ],
  },
  {
    label: "出行",
    icons: [
      "car", "bus", "plane", "bike", "train", "truck", "ship",
      "fuel", "map", "navigation", "compass", "rocket", "tent",
    ],
  },
  {
    label: "购物",
    icons: [
      "shopping-bag", "shopping-cart", "package", "shirt", "gem",
      "glasses", "watch", "backpack", "tag",
    ],
  },
  {
    label: "居家",
    icons: [
      "home", "house", "building-2", "key", "lock", "bed", "bath",
      "lightbulb", "droplets", "flame", "door-open", "wrench", "hammer",
    ],
  },
  {
    label: "健康",
    icons: [
      "heart-pulse", "dumbbell", "activity", "stethoscope", "hospital",
      "pill", "thermometer", "syringe", "heart-handshake",
      "shield", "shield-check",
    ],
  },
  {
    label: "娱乐",
    icons: [
      "film", "music", "tv", "video", "guitar", "gamepad-2", "gamepad",
      "headphones", "camera", "ticket", "dice-5", "clapperboard", "trophy",
    ],
  },
  {
    label: "运动",
    icons: [
      "dumbbell", "mountain", "bike", "snowflake", "waves", "tent", "compass",
    ],
  },
  {
    label: "工作",
    icons: [
      "briefcase", "target", "award", "medal", "flag", "clipboard",
      "list-checks", "file-text", "rocket",
    ],
  },
  {
    label: "学习",
    icons: [
      "graduation-cap", "book-open", "book-marked", "book",
      "pencil", "globe", "microscope",
    ],
  },
  {
    label: "数码",
    icons: [
      "smartphone", "laptop", "monitor", "printer", "phone", "mail",
      "keyboard", "cpu", "hard-drive", "wifi", "zap",
    ],
  },
  {
    label: "自然",
    icons: [
      "leaf", "cloud", "wind", "tree-pine", "sprout", "flower-2",
      "sun", "moon", "sunrise", "snowflake", "waves",
    ],
  },
  {
    label: "宠物",
    icons: ["cat", "dog", "bird", "fish", "baby"],
  },
  {
    label: "节庆",
    icons: [
      "gift", "party-popper", "sparkles", "crown", "star",
      "heart", "smile", "trophy", "award",
    ],
  },
];

/** 全部图标名（用于「全部」分组展示和中文关键词搜索） */
export const ALL_ICON_NAMES = Object.keys(ICON_MAP);
